[package]
name = "llung"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.33"
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
libp2p = { version = "0.56.0", features = ["macros", "tokio", "gossipsub", "mdns", "noise", "tcp", "yamux", "quic", "kad", "relay", "dcutr", "identify", "dns"] }
tokio = { version = "1.53.1", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
