[package]
name = "agent-rt"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
textplots = "0.8.7"
llung-core = { path = "../llung-core" }
wasmtime = { version = "48.0.1", features = ["pooling-allocator"] }
