[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
llung-core = { path = "../llung-core" }
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.30.2"
tokio.workspace = true
taffy = "0.14.0"
unicode-width = "0.2.2"
futures.workspace = true
libp2p.workspace = true
tracing-subscriber.workspace = true
tracing = "0.1.44"
serde.workspace = true
serde_json.workspace = true
image = { workspace = true, features = ["jpeg", "png"] }
chrono = "0.4.45"
uuid = "1.26.1"
rand = "0.10.3"
rand_core = "0.10.1"
