// crates/agent/src/history.rs
use llung_core::network::message::{ChatMessage, MessageKind};

/// A node in the binary summary tree.
#[derive(Clone)]
pub struct SummaryNode {
    /// One-line summary generated by the small model.
    pub summary: String,
    /// Token count of this summary (for budget tracking).
    pub token_count: usize,
    /// Pointer back to the original message(s).
    pub source_range: (usize, usize), // start..end indices in flat history
    /// Left/right children in the binary tree.
    pub left: Option<Box<SummaryNode>>,
    pub right: Option<Box<SummaryNode>>,
    /// If true, the agent has "zoomed" and loaded full text.
    pub zoomed: bool,
    /// The full messages (only populated after zoom).
    pub full_text: Option<String>,
}

pub struct HistoryCompressor {
    /// The cheap model used for summarization (could be a tiny ONNX model).
    backend: Box<dyn Summarizer>,
    /// Max tokens to feed into the expensive model.
    context_budget: usize,
}

impl HistoryCompressor {
    pub fn new(backend: Box<dyn Summarizer>, context_budget: usize) -> Self {
        Self {
            backend,
            context_budget,
        }
    }

    /// Build a binary summary tree from a flat slice of messages.
    pub fn compress(&self, messages: &[ChatMessage]) -> SummaryNode {
        if messages.is_empty() {
            return SummaryNode {
                summary: "(no history)".into(),
                token_count: 2,
                source_range: (0, 0),
                left: None,
                right: None,
                zoomed: false,
                full_text: None,
            };
        }

        if messages.len() == 1 {
            let summary = self.summarize_one(&messages[0]);
            let tokens = estimate_tokens(&summary);
            return SummaryNode {
                summary,
                token_count: tokens,
                source_range: (0, 1),
                left: None,
                right: None,
                zoomed: false,
                full_text: Some(messages[0].content.clone()),
            };
        }

        // Split in half, recurse
        let mid = messages.len() / 2;
        let left = self.compress(&messages[..mid]);
        let right = self.compress(&messages[mid..]);

        let merged_summary = self.merge_summaries(&left.summary, &right.summary);
        let tokens = estimate_tokens(&merged_summary);

        SummaryNode {
            summary: merged_summary,
            token_count: tokens,
            source_range: (left.source_range.0, right.source_range.1),
            left: Some(Box::new(left)),
            right: Some(Box::new(right)),
            zoomed: false,
            full_text: None,
        }
    }

    /// Flatten the summary tree into a string, respecting the 64k token budget.
    /// If a node is zoomed, use its full_text instead of summary.
    pub fn flatten(&self, root: &SummaryNode) -> String {
        let mut parts = Vec::new();
        self.flatten_inner(root, &mut parts);
        parts.join("\n")
    }

    fn flatten_inner(&self, node: &SummaryNode, parts: &mut Vec<String>) {
        if let Some(ref text) = node.full_text {
            parts.push(text.clone());
            return;
        }
        if let Some(ref left) = node.left {
            self.flatten_inner(left, parts);
        }
        parts.push(node.summary.clone());
        if let Some(ref right) = node.right {
            self.flatten_inner(right, parts);
        }
    }

    /// "Zoom" into a summary node: replace the summary with the full message text.
    pub fn zoom(&mut self, node: &mut SummaryNode, messages: &[ChatMessage]) {
        if node.zoomed {
            return;
        }
        let (start, end) = node.source_range;
        let full: Vec<String> = messages[start..end]
            .iter()
            .map(|m| format!("[{}]: {}", m.sender_name, m.content))
            .collect();
        node.full_text = Some(full.join("\n"));
        node.zoomed = true;
        // Recompute token count
        node.token_count = estimate_tokens(node.full_text.as_ref().unwrap());
    }

    fn summarize_one(&self, msg: &ChatMessage) -> String {
        match msg.kind {
            MessageKind::ToolCall {
                ref tool_name,
                ref arguments,
            } => {
                format!(
                    "Called tool '{}' with args: {}",
                    tool_name,
                    arguments.chars().take(60).collect::<String>()
                )
            }
            MessageKind::ToolResponse { ref tool_name, .. } => {
                format!("Tool '{}' returned result.", tool_name)
            }
            _ => {
                // Use the cheap model for human/agent messages
                self.backend.summarize(&msg.content)
            }
        }
    }

    fn merge_summaries(&self, left: &str, right: &str) -> String {
        self.backend.merge(left, right)
    }
}

/// Cheap summarizer trait — implemented by tiny ONNX model or rule-based fallback.
pub trait Summarizer: Send + Sync {
    fn summarize(&self, text: &str) -> String;
    fn merge(&self, left: &str, right: &str) -> String;
}

fn estimate_tokens(text: &str) -> usize {
    // Very rough: 1 token ≈ 0.75 words for English
    text.split_whitespace().count() * 4 / 3
}
