[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
llung-core = { path = "../llung-core" }
libp2p = { version = "0.56.0", features = ["macros", "tokio", "gossipsub", "mdns", "noise", "tcp", "yamux", "quic", "kad", "relay", "dcutr", "identify", "dns"] }
tokio = { version = "1.53.1", features = ["full"] }
dirs.workspace = true
